baseURL = 'https://labudzinski.com/'
languageCode = 'pl-pl'
title = 'Dominik Labudzinski'
enableRobotsTXT = true

[services]
  [services.disqus]
    shortname = 'labudzinskicom'

[module]
  [module.hugoVersion]
    min = '0.120.0'

  [[module.mounts]]
    source = 'content'
    target = 'content'

  [[module.mounts]]
    source = 'static'
    target = 'static'

  [[module.mounts]]
    source = 'layouts'
    target = 'layouts'

  [[module.mounts]]
    source = 'data'
    target = 'data'

  [[module.mounts]]
    source = 'archetypes'
    target = 'archetypes'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    lineNos = false
    noClasses = false
    style = 'monokai'
    tabWidth = 4
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false

[params]
  author = 'Dominik Labudzinski'
  copyright_start = 2019
  description = 'DevOps / Software Architect / Software Engineer / Database Architect / Security Engineer'
  date_format = '2006-01-02'
  back_home_text = 'Back'
  github = 'https://github.com/labudzinski'
  linkedin = 'https://www.linkedin.com/in/dominik-l/'

[taxonomies]
  tag = 'tags'

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[outputs]
  home = ['HTML', 'RSS']
